version: "3.8"
services:
  db:
    image: postgres:15
    container_name: some_postgres
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env
  db_test:
    image: postgres:15
    container_name: some_postgres
    command: -p 5430
    expose:
      - 5430
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: calc_app
    ports:
      - 1:8000
    depends_on:
      - db
      - db_test
